language: python
services:
  - docker

# Run everything in a Fedora container (created in before_install) so that
# we're not fighting with deps on two distros.
# Use the same paths both inside and outside the container so that
# the coverage stuff doesn't get confused.
env:
  DOCKER_RUN="docker run -v $PWD:$PWD --workdir $PWD pykickstart/test-env"

before_install:
  - docker build -t pykickstart/test-env -f Dockerfile.test .

script:
  # Stop after the first failure, to keep the output more readable
  - |
    $DOCKER_RUN make check &&
    $DOCKER_RUN env LANG=C COVERAGE=coverage-3 make coverage &&
    $DOCKER_RUN make docs

notifications:
  email:
    on_success: change
    on_failure: change
