name: Tests and Coverage
# Make sure only one action triggers the job, otherwise pushing to a
# pull-request will run it twice.
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master
      - rhel9-branch
      - rhel8-branch
      - rhel7-branch

jobs:
  unit-tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, "3.10", "3.11"]
        include:
          - python-version: 3.6
            tox-env: py36
          - python-version: 3.7
            tox-env: py37
          - python-version: 3.8
            tox-env: py38
          - python-version: 3.9
            tox-env: py39
          - python-version: "3.10"
            tox-env: py310
          - python-version: "3.11"
            tox-env: py311
    steps:
      - name: "Clone Repository"
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install gettext
        run: sudo apt-get install -y gettext
      - name: Install tox and update pip
        run: python -m pip install --upgrade pip tox
      - name: Run check coverage and docs
        run: tox -e ${{ matrix.tox-env }}
      - name: Coveralls
        if: matrix.python-version == 3.11
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          format: python
          debug: true
